### ISSUE TITLE
sendline() fails in Cygwin

### ISSUE THREAD

**Issue by raczben** [raczben/wexpect#15]
**Sendline fails in cygwin**

**To Reproduce**
Cygwin console:

```
PC /cygdrive/d/wexpect
$ python examples/cmd_wrapper.py
Microsoft Windows [Version 10.0.18362.356]
(c) 2019 Microsoft Corporation. All rights reserved.

D:\wexpect>ls
Traceback (most recent call last):
  File "examples/cmd_wrapper.py", line 34, in <module>
    p.sendline(command)
  File "D:\wexpect\wexpect.py", line 761, in sendline
    n = self.send(s)
  File "D:\wexpect\wexpect.py", line 1447, in send
    c = self.wtty.write(s)
  File "D:\wexpect\wexpect.py", line 1775, in write
    wrote = self.__consin.WriteConsoleInput(records)
pywintypes.error: (6, 'WriteConsoleInput', 'The handle is invalid.')
```

**Expected behavior**
Not to crash

**Environment:**
 - OS Name    Microsoft Windows 10 Home
 - Version      10.0.18362 Build 18362
 - Python 3.7.5
 - 2.3.7.dev8
 - Cygwwin: uname -r :  2.11.2(0.329/5/3)

**Comment by raczben** [comment]
[v3.2.0](https://github.com/raczben/wexpect/releases/tag/v3.2.0) solve this if `WEXPECT_SPAWN_CLASS` environment variable is set to `SpawnPipe` or `SpawnSocket`:

```
export WEXPECT_SPAWN_CLASS=SpawnSocket
```

**Comment by raczben** [comment]
[v4.0.0](https://github.com/raczben/wexpect/releases/tag/v4.0.0) solve this completely, because it's default spawn class is `SpawnPipe`
