### ISSUE TITLE
The logger writes everything twice into the logfile.

### ISSUE THREAD

**Issue by raczben** [raczben/wexpect#28]
**Describe the bug**
The logger writes everything twice into the logfile.

Snippet:

```
2020-02-23 00:00:46,657 - __main__.py:39 - INFO - Starter arguments: Namespace(buffer_size_x=80, buffer_size_y=16000, codepage=None, command=['C:\\Program Files\\Git\\usr\\bin\\cat.EXE'], console_reader_class='ConsoleReaderPipe', host_pid=19440, interact='False', local_echo='True', window_size_x=80, window_size_y=25)
2020-02-23 00:00:46,657 - __main__.py:39 - INFO - Starter arguments: Namespace(buffer_size_x=80, buffer_size_y=16000, codepage=None, command=['C:\\Program Files\\Git\\usr\\bin\\cat.EXE'], console_reader_class='ConsoleReaderPipe', host_pid=19440, interact='False', local_echo='True', window_size_x=80, window_size_y=25)
2020-02-23 00:00:46,657 - console_reader.py:110 - INFO - ConsoleReader started. location D:\betonra\wexpect-tox\dist\wexpect\wexpect\console_reader.pyc
2020-02-23 00:00:46,657 - console_reader.py:110 - INFO - ConsoleReader started. location D:\betonra\wexpect-tox\dist\wexpect\wexpect\console_reader.pyc
2020-02-23 00:00:46,657 - console_reader.py:116 - INFO - Setting console output code page to 1250
2020-02-23 00:00:46,657 - console_reader.py:116 - INFO - Setting console output code page to 1250
2020-02-23 00:00:46,657 - console_reader.py:119 - INFO - Console output code page: 1250
2020-02-23 00:00:46,657 - console_reader.py:119 - INFO - Console output code page: 1250

```

**To Reproduce**
Switch on logger with `set WEXPECT_LOGGER_LEVEL=INFO` and run anything.

**Expected behavior**
Write each log-item once.

**Environment:**
 - windows    10.0.18362 Build 18362
 - Python      3.7.5
 - wexpect     22b2e2ea92ddd78254a8f418652420ed02f76d96

**Comment by nmz787** [comment]
trying to set that ENV var in the script:
```
import os
os.environ['WEXPECT_SPAWN_CLASS'] = 'SpawnPipe'
os.environ['WEXPECT_LOGGER_LEVEL']='INFO'
from wexpect import spawn
from wexpect import TIMEOUT, EOF
```

yields this error at the end of my script
```
Traceback (most recent call last):
  File "C:\misc\my_script_dir\wexpect\host.py", line 312, in __del__
    logger.info('Deleting...')
  File "C:\Python36\lib\logging\__init__.py", line 1308, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Python36\lib\logging\__init__.py", line 1444, in _log
    self.handle(record)
  File "C:\Python36\lib\logging\__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "C:\Python36\lib\logging\__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "C:\Python36\lib\logging\__init__.py", line 865, in handle
    self.emit(record)
  File "C:\Python36\lib\logging\__init__.py", line 1071, in emit
    self.stream = self._open()
  File "C:\Python36\lib\logging\__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Exception ignored in: <bound method SpawnBase.__del__ of <wexpect.host.SpawnPipe object at 0x000002444AD03E48>>
Traceback (most recent call last):
  File "C:\misc\my_script_dir\wexpect\host.py", line 320, in __del__
  File "C:\Python36\lib\logging\__init__.py", line 1320, in warning
  File "C:\Python36\lib\logging\__init__.py", line 1444, in _log
  File "C:\Python36\lib\logging\__init__.py", line 1454, in handle
  File "C:\Python36\lib\logging\__init__.py", line 1516, in callHandlers
  File "C:\Python36\lib\logging\__init__.py", line 865, in handle
  File "C:\Python36\lib\logging\__init__.py", line 1071, in emit
  File "C:\Python36\lib\logging\__init__.py", line 1061, in _open
NameError: name 'open' is not defined
```

**Comment by nmz787** [comment]
this looks relevant to my exception:
https://stackoverflow.com/a/29737870/253127
```
[that user's] code used to work until Python 3.4. I know because I've just run into the same issue, calling open() within __del__. Apparently built-in functions no longer work, because of a change in when __del__ is run as the interpreter shuts down.```

**Comment by raczben** [comment]
@nmz787 , your issue is another logging issue. I suggest to open a new issue for that.
The duplicated logging issue has been solved.

**Comment by raczben** [comment]
[v3.3.1](https://github.com/raczben/wexpect/releases/tag/v3.3.1) fixes this issue.

Upgrade your installation with:

`python -m pip install --upgrade wexpect`
