### ISSUE TITLE
new method failing to work (ENV var)

### ISSUE THREAD

**Issue by nmz787** [raczben/wexpect#34]
Here's the setup
```
from __future__ import unicode_literals

import os
import sys
import time
import json
import shutil
import getpass
import argparse
import subprocess
from ast import literal_eval
from datetime import datetime
import collections
import re

os.environ['WEXPECT_SPAWN_CLASS'] = 'SpawnSocket'
from wexpect import spawn
from wexpect import TIMEOUT, EOF

class stream_splitter(object):
    def __init__(self):
        self.log = open('debug_log.log', 'wb')
        self.last_string_buffer = collections.deque(maxlen=2)

    def multiple_wheel_building_lines(self, string):
        self.last_string_buffer.append(string.strip())
        if all([s.startswith('Building wheel for') for s in self.last_string_buffer]):
            return True
        return False

    def force_decode(self, string, codecs=['cp1252', 'utf8', 'utf-8']):
        if isinstance(string, str):
            return string.encode('utf8')
        for i in codecs:
            try:
                return string.decode(i, errors='replace').encode('utf8')
            except UnicodeDecodeError:
                pass

    def write(self, val):
        if not val:
            return
        val = self.force_decode(val)
        string_val = val.decode('utf8')
        if self.multiple_wheel_building_lines(string_val):
            return
        print(string_val)
        self.log.write(val)

    def read(self):
        pass

    def flush(self):
        self.log.flush()


DEBUG=True
if DEBUG:
    log = stream_splitter()


# later on in the file
shell = spawn('cmd.exe')
time.sleep(1)
shell.sendline('PROMPT {}'.format(unique_prompt))
shell.expect(unique_prompt)
print('*** got cmd prompt')

if DEBUG:
    shell.logfile_read = log

# do more work, running pip installs in the spawned shell, running git clone, running Python based unit-tests of my packages
```

and here's the error:
```
  File "my_script.py", line 453, in start_automation
    shell = spawn('cmd.exe')
  File "C:\misc\my_script_dir\wexpect\host.py", line 1030, in __init__
    interact=interact)
  File "C:\misc\my_script_dir\wexpect\host.py", line 305, in __init__
    self.connect_to_child()
  File "C:\misc\my_script_dir\wexpect\host.py", line 1047, in connect_to_child
    self.sock.connect((self.host, self.port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
Traceback (most recent call last):
  File "C:\misc\my_script_dir\wexpect\host.py", line 314, in __del__
    self.terminate()
  File "C:\misc\my_script_dir\wexpect\host.py", line 453, in terminate
    self.kill()
  File "C:\misc\my_script_dir\wexpect\host.py", line 1096, in kill
    self.send(SIGNAL_CHARS[sig])
  File "C:\misc\my_script_dir\wexpect\host.py", line 624, in send
    return self._send_impl(s)
  File "C:\misc\my_script_dir\wexpect\host.py", line 1042, in _send_impl
    self.sock.sendall(s)
OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
```

If I change the ENV var to `os.environ['WEXPECT_SPAWN_CLASS'] = 'SpawnPipe'`

then my logging from the spawned shell doesn't print with the previously working code in the "old" method (using the `stream_splitter` "object with a `write` method").

**Comment by nmz787** [comment]
(and since the logging doesn't work, I can't really verify if things are working as expected in the spawned shell)

**Comment by nmz787** [comment]
hacking `wexpect\host.py` in the `class SpawnBase` to change `def expect`

from:
```
    def expect(self, pattern, timeout=-1, searchwindowsize=None):
        compiled_pattern_list = self.compile_pattern_list(pattern)
        return self.expect_list(compiled_pattern_list, timeout, searchwindowsize)
```

to
```
    def expect(self, pattern, timeout=-1, searchwindowsize=None):
        compiled_pattern_list = self.compile_pattern_list(pattern)
        retval = self.expect_list(compiled_pattern_list, timeout, searchwindowsize)
        try:
            self.logfile_read.write(self.before)
        except:
            pass
        return retval
```

gets the logging to work again... not sure what the more elegant way to fix this is though... my code has 64 places using `shell.expect`... I could add a wrapper in my code for that call, but it seems a little uglier than I'd like.

Can you suggest something better?

**Comment by raczben** [comment]
Sorry for the delay. I can reproduce the issue, which is a more general issue, in this, v3.3.0 version. However, [here](https://ci.appveyor.com/project/raczben/wexpect/builds/31000176#L624) starts the log of the CI test, which has passed. I'm working on it.

**Comment by raczben** [comment]
3.3.1.dev9 solve this issue:

`pip install wexpect==3.3.1.dev9`

**Comment by raczben** [comment]
[v3.3.1](https://github.com/raczben/wexpect/releases/tag/v3.3.1) fixes this issue.

Upgrade your installation with:

`python -m pip install --upgrade wexpect`
