### ISSUE TITLE
spawn problems on Windows 10

### ISSUE THREAD

**Issue by jsweber502** [raczben/wexpect#39]
On Windows 10, after calling spawn, nothing is received from spawned process except EOF.
Problem occurs from either a script or from shell commands.  64-bit ( build17134.1425)

**To Reproduce**
>>> import wexpect
>>> child = wexpect.spawn('cmd.exe')
>>> print(child)
<wexpect.host.SpawnPipe object at 0x00ED83E8>
command: C:\WINDOWS\system32\cmd.exe
args: ['C:\\WINDOWS\\system32\\cmd.exe']
searcher: None
buffer (last 100 chars): 
before (last 100 chars): None
after: None
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 17168
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
>>> str = child.readline()
>>> print(str)
>>> child.expect('>')
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    child.expect('>')
  File "C:\Users\jweber\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wexpect\host.py", line 732, in expect
    return self.expect_list(compiled_pattern_list, timeout, searchwindowsize)
  File "C:\Users\jweber\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wexpect\host.py", line 745, in expect_list
    return self.expect_loop(searcher_re(pattern_list), timeout, searchwindowsize)
  File "C:\Users\jweber\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wexpect\host.py", line 806, in expect_loop
    raise EOF('EOF flag has been raised.')
wexpect.wexpect_util.EOF: EOF flag has been raised.

**Expected behavior**

**Screenshots**

**Environment:**
 - [windows version]
 - [Python version]
 - [wexpect version]

**Additional context**

**Comment by raczben** [comment]
I develop/test it on Win10, with Python 3.7. I will try to test with 3.8, but I don't believe that this can cause this error.

The `buffer (last 100 chars): ` is empty. This leads me, that the start of the program has a problem. Maybe wexpect cannot find the cmd executable. Please turn on the [logging](https://github.com/raczben/wexpect/wiki/Wexpect-logging), and send me the logfiles.

**Comment by jsweber502** [comment]
Thanks for the reply.  I have attached logfile from following shell commands:

Import wexpect
child = wexpect.spawn(‘cmd.exe’)
child.expect(‘>’)

These immediate produce EOF exception.

**Comment by jsweber502** [comment]
log file:
[wexpect.log.log](https://github.com/raczben/wexpect/files/4714847/wexpect.log.log)

**Comment by jsweber502** [comment]
More info.   Problem was seen on 2 Win10 machines, BUT only when executing in IDLE.   Problem did not occur when running python from cmd prompt.

**Comment by raczben** [comment]
The most of the IDEs are not supported by wexpect. (Wexpect and IDEs create virtual terminals, which can disturb each other.)

Similar to #1 

Some IDE becomes supported with [v4.0.0](https://github.com/raczben/wexpect/releases/tag/v4.0.0), but I use wexpect in natively.
