### ISSUE TITLE
Windows 10 wexpect.spawn('telnet') doesn't seem to work

### ISSUE THREAD

**Issue by NinadRajeVarian** [raczben/wexpect#40]
**Describe the bug**
When I run a telnet client session through wexpect.spawm API, it gives timeout and doesn't match the prompt pattern that I provided. I am using Python 3.7.4.  

My sample code:
```python
def wexpect_telnet():
    print("In wexpect_telnet")
    child = wexpect.spawn('telnet')
    child.expect("Microsoft Telnet> ")
```

I got following error.

```console
C:\PythonWork\Sandbox1>python Keywords.py
In wexpect_telnet
Traceback (most recent call last):
  File "C:\Users\bwn6286\AppData\Local\Programs\Python\Python37\lib\site-packages\wexpect\host.py", line 809, in expect_loop
    raise TIMEOUT('Timeout exceeded in expect_any().')
wexpect.wexpect_util.TIMEOUT: Timeout exceeded in expect_any().

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Keywords.py", line 52, in <module>
    wexpect_telnet()
  File "Keywords.py", line 36, in wexpect_telnet
    child.expect("Microsoft Telnet> ")
  File "C:\Users\bwn6286\AppData\Local\Programs\Python\Python37\lib\site-packages\wexpect\host.py", line 732, in expect
    return self.expect_list(compiled_pattern_list, timeout, searchwindowsize)
  File "C:\Users\bwn6286\AppData\Local\Programs\Python\Python37\lib\site-packages\wexpect\host.py", line 745, in expect_list
    return self.expect_loop(searcher_re(pattern_list), timeout, searchwindowsize)
  File "C:\Users\bwn6286\AppData\Local\Programs\Python\Python37\lib\site-packages\wexpect\host.py", line 843, in expect_loop
    raise TIMEOUT(f'{e}\n{self}')
wexpect.wexpect_util.TIMEOUT: Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x0000019DEB6E7E08>
command: C:\WINDOWS\system32\telnet.EXE
args: ['C:\\WINDOWS\\system32\\telnet.EXE']
searcher: searcher_re:
    0: re.compile("Microsoft Telnet> ")
buffer (last 100 chars):
before (last 100 chars):
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 4540
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2

C:\Users\bwn6286\PythonWork\Sandbox1> 
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - [windows version]
 - [Python version]
 - [wexpect version]

**Additional context**

**Comment by NinadRajeVarian** [comment]
Maybe, something that I am doing wrong here?

**Comment by raczben** [comment]
Hi,

I can reproduce your issue. (Telnet install description [here](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc771275(v=ws.10)).)

But no idea. There are some applications which output's cannot be caught with wexpect. I know that Xilinx's SDK's cannot be controlled with wexpect, but this telnet is new for me. Sorry. Please try other telnet clients, or python build-in socket module.

**Comment by NinadRajeVarian** [comment]
Thanks for your reply. I will try other telnet clients. I will communicate if I come across any issues. For now we can close this issue.
