### ISSUE TITLE
Always TIMEOUT

### ISSUE THREAD

**Issue by Yajo** [raczben/wexpect#42]
**Describe the bug**
I cannot call `wexpect.spawn` because I always get a timeout error.

**To Reproduce**

```
>>> wexpect.spawn('cmd', timeout=10)
Traceback (most recent call last):
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 256, in __del__        
    self.terminate()
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 416, in terminate      
    self.kill()
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 446, in kill
    self.send(SIGNAL_CHARS[sig])
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 600, in send
    return self._send_impl(s)
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 977, in _send_impl     
    win32file.WriteFile(self.pipe, s)
pywintypes.error: (6, 'WriteFile', 'Controlador no válido.')

Exception ignored in: <function SpawnBase.__del__ at 0x000001F77D5E89D0>
Traceback (most recent call last):
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 256, in __del__        
    self.terminate()
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 416, in terminate
    self.kill()
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 446, in kill
    self.send(SIGNAL_CHARS[sig])
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 600, in send
    return self._send_impl(s)
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 977, in _send_impl     
    win32file.WriteFile(self.pipe, s)
pywintypes.error: (6, 'WriteFile', 'Controlador no válido.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 875, in __init__       
    super().__init__(
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 247, in __init__       
    self.connect_to_child()
  File "c:\users\user\source\repos\copier\copier\.venv\src\wexpect\wexpect\host.py", line 897, in connect_to_child
    raise TIMEOUT('Connect to child has been timed out.')
wexpect.wexpect_util.TIMEOUT: Connect to child has been timed out.
```

**Expected behavior**
It should spawn the process and let me do stuff :sweat_smile: 

**Screenshots**

**Environment:**
 - Windows 10
 - Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
 - Tried with latest release from pypi and installing latest commit from git: https://github.com/raczben/wexpect/commit/c8977d8460956d265975fac5fbcd101f2e94c13f

**Additional context**
I'm mainly trying to spawn a python CLI app that runs in a Poetry venv. I guess I could hit #22 or #26, but this one is another bug, as it seems because running `cmd` also fails with the same problem. :man_shrugging:

**Comment by raczben** [comment]
Hi,

As you have found venv is not supported because its [strange behaviour](https://stackoverflow.com/q/61290972/2506522), please checkout [this](https://github.com/raczben/wexpect/issues/26#issuecomment-698335967).

**Comment by testUser235** [comment]
This issue is happening due to the venv wexpect file is not able to get the system path. So try using the Terminal or command line to execute your code.

Happy Coding :)
