### ISSUE TITLE
pywintypes.error: (2, 'CreateFile', '系统找不到指定的文件')

### ISSUE THREAD

**Issue by qyk1995** [raczben/wexpect#54]
**Describe the bug**

Traceback (most recent call last):
  File "C:\Users\dream\PycharmProjects\pythonProject\venv\lib\site-packages\wexpect\host.py", line 878, in connect_to_child
    self.pipe = win32file.CreateFile(
pywintypes.error: (2, 'CreateFile', '系统找不到指定的文件。')

**To Reproduce**

**Expected behavior**
Traceback (most recent call last):
  File "C:\Users\dream\PycharmProjects\pythonProject\venv\lib\site-packages\wexpect\host.py", line 878, in connect_to_child
    self.pipe = win32file.CreateFile(
pywintypes.error: (2, 'CreateFile', '系统找不到指定的文件。')

**Screenshots**
![图片](https://user-images.githubusercontent.com/44867235/180424561-4f7cfcec-b799-4a8a-b9bd-b251e4f28159.png)

**Environment:**
 - [windows version]  Windows 10 专业版(19042.508)
 - [Python version]  3.9.12
 - [wexpect version] 4.0.0

**Additional context**

**Comment by ShiKangBao** [comment]
大佬，咋解决的？
![image](https://user-images.githubusercontent.com/34313868/181934468-a7617ffa-f550-47c5-9c82-ef0fbacf0f2a.png)
spawn 一直被 hangs
