### ISSUE TITLE
Stuck in loop trying to initialize pipe

### ISSUE THREAD

**Issue by Stefanhg** [raczben/wexpect#58]
**Describe the bug**
Hello,
I was working on some tests and then transferred them to a new computer. After transferring i cannot spawn my object.
I went back to 101 and just spawn cmd.exe but that also fails. Tried multiple computers with the same result.

**To Reproduce**
```
import wexpect
child = wexpect.spawn('cmd.exe')
child.expect('>')
```

**Expected behavior**
It simply just being able to execute 'cmd.exe

**Screenshots**

**Environment:**
Windows version: Windows 10 22H2
Python version: Python 3.10.6, tested on 3.8.10
wexpect version: 4.0.0

**Additional context**
If i go back to 3.3.1 it does manage to spawn, but no data is in the buffer child.buffer
I also tried to install tip of wexpect which does not fix the issue.

**Traceback:**
```
D:\Test\test_wexpect>python test_expect.py
Traceback (most recent call last):
  File "C:\Users\shg\AppData\Local\Programs\Python\Python310\lib\site-packages\wexpect\host.py", line 900, in connect_to_child
    self.pipe = win32file.CreateFile(
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Test\test_wexpect\test_expect.py", line 2, in <module>
    child = wexpect.spawn('cmd.exe')
  File "C:\Users\shg\AppData\Local\Programs\Python\Python310\lib\site-packages\wexpect\host.py", line 877, in __init__
    super().__init__(
  File "C:\Users\shg\AppData\Local\Programs\Python\Python310\lib\site-packages\wexpect\host.py", line 248, in __init__
    self.connect_to_child()
  File "C:\Users\shg\AppData\Local\Programs\Python\Python310\lib\site-packages\wexpect\host.py", line 918, in connect_to_child
    time.sleep(0.2)
KeyboardInterrupt
^C
```

**Logfile**
[wexpect_1660.log](https://github.com/raczben/wexpect/files/12726103/wexpect_1660.log)

**Comment by Stefanhg** [comment]
It seems like i found a pattern.
First up virtualenv seems like it is a nogo which I think i have also read somewhere here.
Second you HAVE to install python shared for all users. Then I managed to get it working.
Why? No idea at all.. More testing ongoing

**Comment by Stefanhg** [comment]
I uninstalled all Py versions
Installed Python 3.10.10:
Checked "add Python to Environment variables" and "Install Python 3.10 for all users" in install setup
Afterwards i did pip install wexpect 
And then executed **To Reproduce** 
Result was a success. CMD process was started and working.

So now it comes down to... What can cause this

**Comment by Stefanhg** [comment]
I have a feeling that this is also related to https://github.com/raczben/wexpect/issues/51#issuecomment-877277015 

I am guessing that a venv and user env is the same and therefore both sharing the same problem.
