### ISSUE TITLE
Error importing wexpect: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by zanda8893** [raczben/wexpect#67]
**Describe the bug**
Error while importing

**To Reproduce**
install wexpect 4.0.0
import wexpect

**Expected behavior**
Import completes successfully 

**Log**
```
(venv) PS C:\Users\...> pip3 install wexpect      
Collecting wexpect
  Using cached wexpect-4.0.0-py3-none-any.whl
Requirement already satisfied: pywin32>=220 in c:\users\...\venv\lib\site-packages (from wexpect) (307)
Requirement already satisfied: psutil>=5.0.0 in c:\users\...\venv\lib\site-packages (from wexpect) (6.0.0)
Installing collected packages: wexpect
Successfully installed wexpect-4.0.0
(venv) PS C:\Users...> py
Python 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wexpect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\...\venv\Lib\site-packages\wexpect\__init__.py", line 4, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
>>>
```

**Environment:**
 - Windows 11
 - Python 3.12.7
 - wexpect 4.0.0

**Additional context**
Same issue when using wexpect 3.3.2

**Comment by zanda8893** [comment]
Fixed with `pip install setuptools`
