### ISSUE TITLE
The python examples failes

### ISSUE THREAD

**Issue by raczben** [raczben/wexpect#7]
### Reproduce

Run the python.py example

`python examples\python.py`

### Output:

```
D:\bt\wexpect>python examples\python.py
Traceback (most recent call last):
  File "examples\python.py", line 26, in <module>
    p.sendline('Bob')
  File "C:\Users\usr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wexpect.py", line 999, in sendline
    n = n + self.send (os.linesep)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by raczben** [comment]
Commit `813a462` solved the issue.
