### ISSUE TITLE
AttributeError: 'Wtty' object has no attribute '_Wtty__consout'

### ISSUE THREAD

**Issue by raczben** [raczben/wexpect#8]
**Describe the bug**

Reported by Shay Ceasary.

```
>>> import wexpect
>>> child = wexpect.spawn('cmd.exe')
>>> child.expect('>')

Traceback (most recent call last):
  File "C:\Users\shayc\PycharmProjects\Training\venv\lib\site-packages\wexpect.py", line 2323, in read_nonblocking
    s = self.readConsoleToCursor()
  File "C:\Users\shayc\PycharmProjects\Training\venv\lib\site-packages\wexpect.py", line 2229, in readConsoleToCursor
    if not self.__consout:

AttributeError: 'Wtty' object has no attribute '_Wtty__consout'
```

**To Reproduce**

```
import wexpect
child = wexpect.spawn('cmd.exe')
child.expect('>')
```

**Environment:**
 - Microsoft Windows 10 Pro (10.0.17134 Build 17134)
 - Python 3.7
 - wexpect version ???

**Comment by raczben** [comment]
Hi,

I cannot reproduce the bug, with
 - `wexpect==v2.3.5`
 - `python 3.7.3`
 - Win 10 Pro (1903) (18362.295)
 - 8th Gen Core i7

```
D:\bt\wexpect-issue08>c:\Python373\python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wexpect
>>> child = wexpect.spawn('cmd.exe')
>>> child.expect('>')
0
>>> child.before
'Microsoft Windows [Version 10.0.18362.295]\r\n(c) 2019 Microsoft Corporation. All rights reserved.\r\n\r\nD:\\bt\\wexpect-issue08'
>>> exit()

D:\bt\wexpect-issue08>git status
HEAD detached at v2.3.5
nothing to commit, working tree clean
```

I had seen the referenced exception earlier in the past, but I cannot remember the solution.

**Comment by raczben** [comment]
I have investigate a bit on this issue. The `__consout` variable is assigned in the [`switchTo()` function](https://github.com/raczben/wexpect/blob/2c978c65643314e0bf96ce3ecc145d6b8bc0c5f4/wexpect.py#L2053).
If you get this error the error must be originated in this, `switchTo()` function.
The only case, which can result this issue is in the [2072 line](https://github.com/raczben/wexpect/blob/2c978c65643314e0bf96ce3ecc145d6b8bc0c5f4/wexpect.py#L2072)
Please try to remove, this *"exception handling"*, and raise the original exception after re AttachConsole(), and send me the exception.

**Comment by raczben** [comment]
This error happens, when the child has died / not started.
See #3 , which describes this issue.

**Comment by raczben** [comment]
Non reproducible
